### ISSUE TITLE
Exclude Flametongue Weapon Rank 9

### ISSUE THREAD

**Issue by wheezy1749** [valkyrnstudios/RankSentinel#66] opened 2022-10-18 21:23 UTC
Rank 9 and 10 don't share internal cooldowns so a minmax shammy will use one on each weapon. Please exclude rank 9.

Or, better yet, I think this addon should have a feature to BLOCK or set a blacklist to spells for whispers from others using the addon. Obviously that's more work but its annoying being whisper spammed because I'm playing my class correctly.

**Comment by SabreValkyrn** [comment] 2022-10-18 21:25
Flametongue Rank 9 was excluded 11 days ago in [v2.2.1](https://github.com/valkyrnstudios/RankSentinel/releases/tag/v2.2.1).

Duplicate of #63

**Closed by SabreValkyrn** 2022-10-18 21:25 UTC
